// Assemble chapter files from transcription fragments.
// Fragments live in data/frag/chNN-pK.js (one chapter part) and data/frag/chNN-review.js,
// each calling N2F({...}). Usage: node tools/merge.js 1 2 3 …   (default: every chapter with fragments)
//
//   part fragment:   N2F({ ch: 1, part: 0, head: { genre, title, canDo }, label, canDo, sample, points: [...], check })
//                    (`head` only in part 0)
//   review fragment: N2F({ ch: 1, review: [ ReviewSection, … ] })
const fs = require("fs"), path = require("path");
const root = path.resolve(__dirname, "..");
const fragDir = path.join(root, "data/frag");
const frags = [];
global.N2F = (f) => frags.push(f);
for (const f of fs.readdirSync(fragDir).filter((x) => /^ch\d\d-.*\.js$/.test(x)).sort()) {
  const before = frags.length;
  require(path.join(fragDir, f));
  frags.slice(before).forEach((x) => (x.__file = f));
}
const want = process.argv.slice(2).map(Number);
const chIds = [...new Set(frags.map((f) => f.ch))].filter((c) => !want.length || want.includes(c)).sort((a, b) => a - b);

for (const ch of chIds) {
  const mine = frags.filter((f) => f.ch === ch);
  const parts = mine.filter((f) => f.part != null).sort((a, b) => a.part - b.part);
  const review = mine.find((f) => f.review);
  const head = (parts.find((p) => p.part === 0) || {}).head;
  if (!head) { console.log(`ch${ch}: missing part 0 / head — skipped`); continue; }
  const out = {
    id: ch,
    genre: head.genre,
    title: head.title,
    canDo: head.canDo || [],
    parts: parts.map((p) => {
      const o = { label: p.label || "" };
      if (p.canDo) o.canDo = p.canDo;
      o.sample = p.sample;
      o.points = p.points;
      if (p.check) o.check = p.check;
      return o;
    }),
    review: review ? review.review : [],
  };
  const file = path.join(root, "data/chapters", `ch${String(ch).padStart(2, "0")}.js`);
  const src = `// Generated by tools/merge.js from data/frag/ch${String(ch).padStart(2, "0")}-*.js — edit the fragments, not this file.\nN2.register(${JSON.stringify(out, null, 2)});\n`;
  fs.writeFileSync(file, src);
  console.log(`ch${ch}: parts ${parts.map((p) => p.part).join(",")} (${parts.map((p) => p.points.length).join("+")} points), review ${review ? review.review.length + " sections" : "MISSING"} → ${path.relative(root, file)}`);
}
